# Generated by Django 4.0.1 on 2022-02-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='questionCount',
            field=models.IntegerField(default=0),
        ),
    ]
