# Generated by Django 4.0.1 on 2022-02-21 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_score_questioncount'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='quiz',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.quiz'),
        ),
    ]
